//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWFEntities : DbContext
    {
        public SWFEntities()
            : base("name=SWFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppointmentDiary> AppointmentDiaries { get; set; }
        public DbSet<tblAssignedUser> tblAssignedUsers { get; set; }
        public DbSet<tUser> tUsers { get; set; }
        public DbSet<tblTask> tblTasks { get; set; }
    }
}
