//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTask
    {
        public long TaskId { get; set; }
        public string TaskName { get; set; }
        public System.DateTime TaskTime { get; set; }
        public string SpecificTime { get; set; }
        public string SpecialRequest { get; set; }
        public bool IsSpecificTime { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string AssignedTo { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
