//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        public int intUserId { get; set; }
        public string strFirstName { get; set; }
        public string strLastName { get; set; }
        public string strUserName { get; set; }
        public string strPassword { get; set; }
        public int intBaseRoleId { get; set; }
        public System.DateTime dtCreatedOn { get; set; }
        public Nullable<System.DateTime> dtModifiedOn { get; set; }
        public string strEmail { get; set; }
        public string strAddress { get; set; }
        public string strPhoneNumber { get; set; }
        public string strRefCode { get; set; }
        public string strBestWay { get; set; }
        public bool blActive { get; set; }
    }
}
